apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: shrutik15/spe-final-springboot:latest
          ports:
          - containerPort: 5000
          volumeMounts:
          - name: image-volume
            mountPath: /mnt/data
      volumes:
      - name: image-volume
        persistentVolumeClaim:
          claimName: image-volume-pvc
